require:
  - rubocop-jekyll

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - '_site/**/*'
    - '.bundle/**/*'
    - 'node_modules/**/*'

# Jekyll-specific
Jekyll/NoPutsAllowed:
  Enabled: true
